version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flashcards_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Optional: Expose PostgreSQL port for direct access from host
    networks:
    - shared_network

  app:
    build: .
    ports:
      - "37894:37894"  # Expose Flask's port to the host
    environment:
      - DB_HOST=db
      - DB_NAME=flashcards_db
      - DB_USER=user
      - DB_PASS=password
      - FLASK_ENV=development
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=37894 # Command to start the Flask app
    networks:
      - shared_network

volumes:
  db_data:
networks:
  shared_network:
    external: true